datasource:
  url: "jdbc:postgresql://localhost:5432/postgres?currentSchema=fucking_great_advice"
  driver: "org.postgresql.Driver"
  user: "postgres"
  password: "passw0rd"
  schema:
    createOnStartup: "true"
    ddlScript: "schema-postgresql.sql"







